name: build-image
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [{dir: AlmaLinux9,suffix: alma9}]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: lowercase owner name
        run: |
            echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
            OWNER: '${{ github.repository_owner }}'
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{env.OWNER_LC}}/k4-dummy
      - name: Build and Push (k4-spack)
        id: docker_build_k4-spack
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./${{matrix.os.dir}}
          file: ./${{matrix.os.dir}}/Dockerfile-spack
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}
            REPOSITORY=ghcr.io/${{env.OWNER_LC}}
          tags: ghcr.io/${{env.OWNER_LC}}/k4-spack:${{steps.meta.outputs.version}}-${{matrix.os.suffix}}
      - name: Build and Push (k4-sim)
        id: docker_build_k4-sim
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./${{matrix.os.dir}}
          file: ./${{matrix.os.dir}}/Dockerfile-base
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}
            REPOSITORY=ghcr.io/${{env.OWNER_LC}}
          tags: ghcr.io/${{env.OWNER_LC}}/k4-base:${{steps.meta.outputs.version}}-${{matrix.os.suffix}}
